import { Request, Response } from 'express'
import { prisma } from '@repo/db'
import { uploadResume } from '../lib/gcs'
import { enqueueInterviewInvite } from '../lib/emailQueue'
// Import from lib directly to avoid pdf-parse's startup self-test which reads a missing test PDF
// eslint-disable-next-line @typescript-eslint/no-require-imports
const pdfParse: (buffer: Buffer) => Promise<{ text: string }> = require('pdf-parse/lib/pdf-parse')
import { v4 as uuidv4 } from 'uuid'

export const applyToPortal = async (req: Request, res: Response) => {
    try {
        const { portalId } = req.params
        const { name, email, phone, linkedIn, coverLetter } = req.body
        const file = req.file

        if (!name || !email) {
            res.status(400).json({ success: false, message: 'Name and email are required' })
            return
        }

        if (!file) {
            res.status(400).json({ success: false, message: 'Resume PDF is required' })
            return
        }

        const portal = await prisma.portal.findUnique({ where: { id: portalId } })
        if (!portal) {
            res.status(404).json({ success: false, message: 'Portal not found' })
            return
        }

        // Extract text from PDF
        let resumeText = ''
        try {
            const parsed = await pdfParse(file.buffer)
            resumeText = parsed.text
        } catch {
            resumeText = ''
        }

        // Upload resume to GCS
        const fileId = uuidv4()
        const gcsPath = `resumes/${portalId}/${fileId}.pdf`
        let resumeUrl = ''
        try {
            resumeUrl = await uploadResume(file.buffer, gcsPath)
        } catch (err) {
            console.error('[candidate] GCS upload failed:', err)
            // Store a placeholder if GCS is not configured
            resumeUrl = `gcs://${gcsPath}`
        }

        // Create candidate record (interviewToken auto-generated by DB default)
        const candidate = await prisma.candidate.create({
            data: {
                name,
                email,
                phone: phone || null,
                linkedIn: linkedIn || null,
                coverLetter: coverLetter || null,
                resumeUrl,
                resumeText,
                portalId,
            },
        })

        // Enqueue interview invite email
        enqueueInterviewInvite(email, name, portalId, candidate.interviewToken).catch((err) =>
            console.error('[candidate] failed to enqueue interview invite:', err)
        )

        res.status(200).json({
            success: true,
            message: 'Application submitted! Check your email for your interview link.',
        })
    } catch (error) {
        console.error('[candidate] applyToPortal error:', error)
        res.status(500).json({ success: false, message: 'Internal server error' })
    }
}

export const getCandidatesByPortal = async (req: Request, res: Response) => {
    try {
        const { portalId } = req.params
        const candidates = await prisma.candidate.findMany({
            where: { portalId },
            select: {
                id: true,
                name: true,
                email: true,
                phone: true,
                linkedIn: true,
                coverLetter: true,
                resumeUrl: true,
                createdAt: true,
            },
            orderBy: { createdAt: 'desc' },
        })
        res.status(200).json({ success: true, data: candidates })
    } catch (error) {
        console.error('[candidate] getCandidatesByPortal error:', error)
        res.status(500).json({ success: false, message: 'Internal server error' })
    }
}

export const getCandidateByToken = async (req: Request, res: Response) => {
    try {
        const { token } = req.params
        const candidate = await prisma.candidate.findUnique({
            where: { interviewToken: token },
            select: {
                name: true,
                email: true,
                resumeText: true,
                linkedIn: true,
                portalId: true,
            },
        })

        if (!candidate) {
            res.status(404).json({ success: false, message: 'Candidate not found' })
            return
        }

        res.status(200).json({ success: true, data: candidate })
    } catch (error) {
        console.error('[candidate] getCandidateByToken error:', error)
        res.status(500).json({ success: false, message: 'Internal server error' })
    }
}
